package(default_visibility = ["//visibility:public"])

java_library(
  name = "client",
  srcs = glob(["*.java"]),
  deps = [
    "//java/de/ofahrt/catfish/utils",
    "//third_party/servlet-api",
  ],
)
