package(default_visibility = ["//visibility:public"])

java_library(
    name = "client",
    srcs = glob(["*.java"]),
    deps = [
        "//java/de/ofahrt/catfish/internal",
        "//java/de/ofahrt/catfish/internal/network",
        "//java/de/ofahrt/catfish/model",
        "//java/de/ofahrt/catfish/model/network",
        "//java/de/ofahrt/catfish/utils",
    ],
)
