package(default_visibility = ["//visibility:public"])

java_library(
  name = "fastcgi",
  srcs = glob(["*.java"]),
  deps = [
    "//java/de/ofahrt/catfish/model",
    "//third_party/servlet-api",
  ],
)
