import java.util.*;

final class Emit {
  java.nio.file.Path proofDir; // one file per obligation, tactic block only
  final List<String> leanImports = new ArrayList<>(); // Lean modules to import + open
  int proved = 0, unproved = 0;
  final List<String> open = new ArrayList<>();
  private final Vcg v;
  private final ClassFile cf;
  private final String method;
  private final String javaFile;
  private final StringBuilder sb = new StringBuilder();
  private final List<int[]> map = new ArrayList<>(); // {leanLine, javaLine, bytecodeOffset}
  private int line = 1;
  private int cuts = 0;

  Emit(Vcg v, ClassFile cf, String method, String javaFile) {
    this.v = v;
    this.cf = cf;
    this.method = method;
    this.javaFile = javaFile;
  }

  int cutCount() {
    return cuts;
  }

  private void out(String s) {
    sb.append(s).append('\n');
    line += s.chars().filter(c -> c == '\n').count() + 1;
  }

  private int javaLine(int off) {
    var e = v.m.lines.floorEntry(off);
    return e == null ? 0 : e.getValue();
  }

  String lean() {
    out("/- GENERATED by jvmlean from " + javaFile + " (" + cf.thisClass + "." + method + ")");
    out("   Do not edit.  Edit the Verify.* strings in the Java source instead. -/");
    out("import Jvm.Semantics");
    for (String s : leanImports) out("import " + s);
    out("");
    out("namespace Generated." + cf.thisClass + "." + method);
    StringBuilder opens = new StringBuilder("open Jvm");
    for (String s : leanImports) opens.append(' ').append(s);
    out(opens.toString());
    out("set_option maxHeartbeats 4000000");
    out("set_option linter.unusedVariables false");
    out("");
    program();
    out("");
    for (Vcg.Ins i : v.ins) if (i.isMarkerLdc) invDef(i);
    for (Vcg.Path p : v.paths) if (!p.endsInReturn) obligation(p);
    out("");
    out("/- Audit: every obligation must rest only on propext/Classical.choice/Quot.sound.");
    out("   A `sorryAx` here means something was left open, including via a spec string. -/");
    for (Vcg.Path p : v.paths)
      if (!p.endsInReturn)
        out(
            "#print axioms obl_"
                + v.ins.get(p.fromIdx).cutName
                + "_"
                + v.ins.get(p.toIdx).cutName
                + "_"
                + tag(p));
    out("");
    out("end Generated." + cf.thisClass + "." + method);
    return sb.toString();
  }

  private void program() {
    out("/-- Transcription of the bytecode.  Index = position in the instruction");
    out("    stream; the comment gives the real bytecode offset. -/");
    out("def P : Nat → Option Instr");
    for (Vcg.Ins i : v.ins) {
      String body = leanOf(i);
      out(
          String.format(
              "  | %-4d => some (%s)%s",
              i.idx,
              body,
              "   -- @" + i.off + (i.isMarkerLdc ? "  <-- cut point (" + i.markerKind + ")" : "")));
    }
    out("  | _    => none");
  }

  private String leanOf(Vcg.Ins i) {
    return switch (i.kind) {
      case "goto" -> ".goto " + v.offToIdx.get(i.target);
      case "ifcmp" -> ".ifcmp " + i.callee + " " + v.offToIdx.get(i.target);
      case "ifz" -> ".ifz " + i.callee + " " + v.offToIdx.get(i.target);
      default -> i.lean;
    };
  }

  /** Binding prelude: source-level names for locals, so spec strings read naturally. */
  /** Bind only the locals whose LVT scope covers this offset, so slot reuse does not shadow. */
  private void prelude(int off, int retSlot) {
    Set<String> bound = new HashSet<>();
    for (var lv : v.m.locals) {
      if (!lv.covers(off) || !bound.add(lv.name)) continue;
      if (lv.slot == 0 && v.m.desc.startsWith("([B")) {
        out("  let " + lv.name + " : Jvm.Arr := s.arr");
      } else {
        out("  let " + lv.name + " : Int := s.loc " + lv.slot);
      }
    }
    if (retSlot >= 0) out("  let ret : Int := s.loc " + retSlot);
  }

  private void invDef(Vcg.Ins i) {
    cuts++;
    int jl = javaLine(i.off);
    out("");
    out(
        "/-- "
            + i.markerKind
            + " at bytecode offset "
            + i.off
            + ", "
            + javaFile
            + ":"
            + jl
            + " -/");
    out("def inv_" + i.cutName + " (s : State) : Prop :=");
    prelude(i.off, i.retSlot);
    map.add(new int[] {line, jl, i.off});
    // spliced verbatim; each source line of the spec string gets its own Lean line
    out("  (" + i.specString.strip().replace("\n", "\n   ") + ")");
  }

  private void obligation(Vcg.Path p) {
    Vcg.Ins a = v.ins.get(p.fromIdx), b = v.ins.get(p.toIdx);
    out("");
    out(
        "/-- "
            + javaFile
            + ":"
            + javaLine(a.off)
            + " -> "
            + javaFile
            + ":"
            + javaLine(b.off)
            + "   (bytecode "
            + a.off
            + " -> "
            + b.off
            + ", "
            + p.sym.steps
            + " steps) -/");
    for (String s : dedup(p.sym.side)) out("--   side condition: " + s);
    out("theorem obl_" + a.cutName + "_" + b.cutName + "_" + tag(p) + " (s s' : State)");
    out("    (hinv : inv_" + a.cutName + " s) (hpc : s.pc = " + a.idx + ") (hstk : s.stk = [])");
    int n = 0;
    for (String c : p.sym.conds) out("    (c" + (n++) + " : " + c + ")");
    out("    (hrun : run P " + p.sym.steps + " s = some s') :");
    out("    inv_" + b.cutName + " s' := by");
    String name = "obl_" + a.cutName + "_" + b.cutName + "_" + tag(p);
    String body = null;
    if (proofDir != null) {
      java.nio.file.Path f = proofDir.resolve(name + ".lean");
      if (java.nio.file.Files.exists(f)) {
        try {
          body = java.nio.file.Files.readString(f);
        } catch (java.io.IOException e) {
          throw new RuntimeException(e);
        }
      }
    }
    if (body == null) {
      out("  sorry");
      unproved++;
      open.add(name + "  (" + javaFile + ":" + javaLine(a.off) + ")");
    } else {
      out(body.stripTrailing().indent(2).stripTrailing());
      proved++;
    }
  }

  private static List<String> dedup(List<String> in) {
    return new ArrayList<>(new LinkedHashSet<>(in));
  }

  /** Distinguish multiple paths between the same pair of cut points. */
  private String tag(Vcg.Path p) {
    int k = 0;
    for (Vcg.Path q : v.paths) {
      if (q == p) break;
      if (q.fromIdx == p.fromIdx && q.toIdx == p.toIdx) k++;
    }
    return String.valueOf(k);
  }

  String sourceMap() {
    StringBuilder j =
        new StringBuilder("{\n  \"source\": \"" + javaFile + "\",\n  \"entries\": [\n");
    for (int i = 0; i < map.size(); i++) {
      int[] e = map.get(i);
      j.append(
          String.format(
              "    {\"leanLine\": %d, \"javaLine\": %d, \"offset\": %d}%s%n",
              e[0], e[1], e[2], i + 1 < map.size() ? "," : ""));
    }
    return j.append("  ]\n}\n").toString();
  }
}
