load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "network",
    srcs = glob(["*.java"]),
    exports = ["//third_party/jspecify"],
    deps = ["//third_party/jspecify"],
)
