package(default_visibility = ["//visibility:public"])

java_library(
  name = "bridge",
  srcs = glob(["*.java"]),
  deps = [
    "//java/de/ofahrt/catfish",
    "//java/de/ofahrt/catfish/model",
    "//java/de/ofahrt/catfish/model/server",
    "//java/de/ofahrt/catfish/utils",
    "//third_party/servlet-api",
  ],
)
