package(default_visibility = ["//visibility:public"])

java_library(
    name = "server",
    srcs = glob(["*.java"]),
    deps = [
        "//java/de/ofahrt/catfish/model",
        "//java/de/ofahrt/catfish/model/network",
    ],
)
